// The steps: layers (inside the library), home (user folders), projects (other repos), unlink, status.
import fs from "node:fs";
import path from "node:path";
import { folderHash, isDir, isLink, isSkillDir, lexists, linkTarget, real, samePath, under } from "./fs.js";
import { RESERVED, type Harness } from "./harnesses.js";
import { Library, sidecarFor } from "./library.js";
import { ensureLink, Report } from "./plan.js";

const GITIGNORE_HEADER = "# Generated by skills-sync: links to this library's own skills under skills/. Do not edit.\n";

/** The working set plus every own skill by its folder name, whether or not its .agents link exists yet. */
function workingSetWithOwn(lib: Library): Map<string, string> {
  const working = lib.workingSet();
  for (const s of lib.scanOwn().skills) if (!working.has(s.name)) working.set(s.name, s.dir);
  return working;
}

/** Inside the library: .agents/skills links for own skills, one project layer per non-universal harness, sidecars. */
export function layers(lib: Library, harnesses: Harness[], report: Report, sidecars = true): void {
  const scan = lib.scanOwn();
  const own = scan.skills;
  const names = new Set(own.map((s) => s.name));
  // a folder under a group that is not a skill: said once here, by the step that owns skills/, never linked
  for (const i of scan.ignored) report.add({ kind: "conflict", path: i.path, note: i.note });
  for (const s of own) ensureLink(report, path.join(lib.agents, s.name), s.dir, lib.root, "own skill");
  if (isDir(lib.agents)) {
    for (const n of fs.readdirSync(lib.agents)) {
      const p = path.join(lib.agents, n);
      if (!isLink(p)) continue;
      const t = linkTarget(p);
      // a name still in own is ensureLink's business (it retargets a moved skill); any other link into skills/ is stale
      if (t && under(t, lib.own) && !names.has(n))
        report.add({ kind: "remove", path: p, note: "stale link to a removed own skill" });
    }
  }
  const gi = path.join(lib.agents, ".gitignore");
  const body = GITIGNORE_HEADER + own.map((s) => `/${s.name}/\n`).join("");
  if (!fs.existsSync(gi) || fs.readFileSync(gi, "utf8") !== body)
    report.add({ kind: "write", path: gi, payload: body, note: `${own.length} entries` });
  else report.add({ kind: "skip", path: gi, note: "ok" });

  if (sidecars) {
    for (const s of own) {
      const file = path.join(s.dir, "agents", "openai.yaml");
      if (fs.existsSync(file)) {
        report.add({ kind: "skip", path: file, note: "exists" });
        continue;
      }
      const yaml = sidecarFor(s.dir);
      if (yaml)
        report.add({ kind: "write", path: file, payload: yaml, note: "Codex sidecar from SKILL.md frontmatter" });
    }
  }

  const working = workingSetWithOwn(lib); // .agents links not applied yet
  for (const h of harnesses) {
    if (h.universal) continue;
    const layer = path.join(lib.root, h.projectSkills);
    for (const [n, target] of [...working].sort()) {
      const link = path.join(layer, n);
      if (lexists(link) && !isLink(link) && isSkillDir(link))
        report.add({ kind: "replace-copy", path: link, target, note: "stale copy in a generated layer" });
      else ensureLink(report, link, target, lib.root, `${h.name} layer`);
    }
    if (isDir(layer)) {
      for (const n of fs.readdirSync(layer)) {
        const p = path.join(layer, n);
        if (!working.has(n) && isLink(p)) {
          const t = linkTarget(p);
          if (t && under(t, lib.root)) report.add({ kind: "remove", path: p, note: "no longer in .agents/skills" });
        }
      }
    }
  }
}

/**
 * One link per skill in each harness's user skills folder. `plugins` names, per harness id, the skills a verified
 * plugin carries there (skill -> plugin id): those get no link, and a link this tool made for one is removed.
 */
export function home(
  lib: Library,
  harnesses: Harness[],
  report: Report,
  plugins: Map<string, Map<string, string>> = new Map(),
): void {
  const working = workingSetWithOwn(lib);
  for (const h of harnesses) {
    const carried = plugins.get(h.id) ?? new Map<string, string>();
    for (const [n, target] of [...working].sort()) {
      if (RESERVED.has(n) || carried.has(n)) continue;
      ensureLink(report, path.join(h.userSkills, n), target, lib.root, `${h.name} user folder`);
    }
    if (isDir(h.userSkills)) {
      for (const n of fs.readdirSync(h.userSkills)) {
        const p = path.join(h.userSkills, n);
        if ((working.has(n) && !carried.has(n)) || !isLink(p)) continue;
        const t = linkTarget(p);
        if (t && under(t, lib.root))
          report.add({
            kind: "remove",
            path: p,
            note: carried.has(n) ? `carried by plugin ${carried.get(n)}` : "skill no longer in the library",
          });
      }
    }
  }
}

export function unlink(lib: Library, harnesses: Harness[], report: Report): void {
  for (const h of harnesses) {
    if (!isDir(h.userSkills)) continue;
    for (const n of fs.readdirSync(h.userSkills)) {
      const p = path.join(h.userSkills, n);
      if (!isLink(p)) continue;
      const t = linkTarget(p);
      if (t && under(t, lib.root)) report.add({ kind: "remove", path: p, note: "made by skills-sync" });
    }
  }
}

/** Git repos directly under `dir`, the library excluded. */
export function findProjects(dir: string, lib: Library): string[] {
  if (!isDir(dir)) return [];
  return fs
    .readdirSync(dir)
    .map((n) => path.join(dir, n))
    .filter((p) => isDir(p) && fs.existsSync(path.join(p, ".git")) && !samePath(real(p), real(lib.root)))
    .sort();
}

export function isRepo(dir: string): boolean {
  return fs.existsSync(path.join(dir, ".git"));
}

/**
 * Give a project its skills. Link mode: one link per skill per harness layer, hidden from git through
 * .git/info/exclude. Copy mode: real folders, meant to be committed.
 */
export function projects(
  lib: Library,
  harnesses: Harness[],
  targets: string[],
  names: string[] | null,
  mode: "link" | "copy",
  report: Report,
): void {
  const working = workingSetWithOwn(lib);
  const chosen = [...working].filter(([n]) => !names || names.includes(n)).sort();
  const layersFor = (h: Harness) => h.projectSkills;
  const seenLayers = new Set<string>();
  const layerDirs = harnesses.map(layersFor).filter((l) => (seenLayers.has(l) ? false : (seenLayers.add(l), true)));
  for (const proj of targets) {
    const excludes: string[] = [];
    for (const layer of layerDirs) {
      for (const [n, src] of chosen) {
        const dst = path.join(proj, layer, n);
        if (mode === "link") {
          if (lexists(dst) && !isLink(dst))
            report.add({
              kind: "conflict",
              path: dst,
              note: "a real folder is in the way (a committed copy?); left alone",
            });
          else ensureLink(report, dst, src, lib.root, "project");
          excludes.push("/" + path.join(layer, n).replace(/\\/g, "/") + "/");
        } else if (isLink(dst))
          report.add({ kind: "conflict", path: dst, note: "is a link; a committed copy must be a real folder" });
        else if (isDir(dst) && folderHash(dst) === folderHash(src)) report.add({ kind: "skip", path: dst, note: "ok" });
        else report.add({ kind: "copy", path: dst, target: src });
      }
    }
    if (mode === "link" && excludes.length)
      report.add({
        kind: "exclude",
        path: proj,
        payload: excludes,
        note: `${excludes.length} entries in .git/info/exclude`,
      });
  }
}

export interface Status {
  library: string;
  own: string[];
  /** each own skill with its plugin id (the group it sits in; null when flat) and its path under the library */
  ownSkills: Array<{ name: string; plugin: string | null; path: string }>;
  thirdParty: string[];
  missingFromLock: string[];
  layers: Record<string, { linked: number; missing: string[] }>;
  /** per user folder: links made, skills a verified plugin carries there instead (plugin form), skills that have neither */
  user: Record<string, { linked: number; plugin: number; missing: string[] }>;
}

export function status(lib: Library, harnesses: Harness[], carried: Map<string, Set<string>> = new Map()): Status {
  const scan = lib.scanOwn().skills;
  const own = scan.map((s) => s.name);
  const working = lib.workingSet();
  const names = [...new Set([...own, ...working.keys()])].sort();
  const linkedInto = (dir: string) => {
    const linked = names.filter((n) => {
      const p = path.join(dir, n);
      const t = isLink(p) ? linkTarget(p) : null;
      return !!t && under(t, lib.root);
    });
    return { linked: linked.length, missing: names.filter((n) => !linked.includes(n)) };
  };
  const out: Status = {
    library: lib.root,
    own,
    ownSkills: scan.map((s) => ({
      name: s.name,
      plugin: s.plugin,
      path: path.relative(lib.root, s.dir).replace(/\\/g, "/"),
    })),
    thirdParty: [...working.keys()].filter((n) => !own.includes(n)),
    missingFromLock: lib.missingFromLock(),
    layers: {},
    user: {},
  };
  for (const h of harnesses) {
    if (!h.universal) out.layers[h.projectSkills] = linkedInto(path.join(lib.root, h.projectSkills));
    const u = linkedInto(h.userSkills);
    const inPlugins = carried.get(h.id) ?? new Set<string>();
    out.user[h.userSkills] = {
      linked: u.linked,
      plugin: names.filter((n) => inPlugins.has(n)).length,
      missing: u.missing.filter((n) => !inPlugins.has(n)),
    };
  }
  return out;
}
