#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# oneezy/tools#14: the two board clicks GitHub keeps browser-only, then the three tokens the status
# and sizing workflows need. Tokens go to a file outside the repo (this repo has no .gitignore) and
# to GitHub Actions secrets on oneezy/tools; never into code.

TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-$HOME/.oneezy/secrets.env}"
mkdir -p "$(dirname "$ENV_FILE")"
cd "$(dirname "$0")/../.."          # repo root, so gh secret set targets oneezy/tools
REPO="oneezy/tools"
PROJECT_URL="https://github.com/users/oneezy/projects/4"

autoadd_on() {
  gh api graphql -f query='{ user(login:"oneezy"){ projectV2(number:4){ workflows(first:20){ nodes { name enabled } } } } }' \
    --jq '.data.user.projectV2.workflows.nodes[] | select(.name=="Auto-add to project" and .enabled) | .name' 2>/dev/null | grep -q . || return 1
}

# verify_pat TOKEN LOGIN: the token belongs to LOGIN and carries project + repo.
verify_pat() {
  local login scopes
  login=$(GH_TOKEN="$1" gh api user --jq .login 2>/dev/null || true)
  scopes=$(GH_TOKEN="$1" gh api -i user 2>/dev/null | grep -i '^x-oauth-scopes:' | tr -d '\r' || true)
  if [[ "$login" != "$2" ]]; then warn "that token belongs to '${login:-nobody}', not $2"; return 1; fi
  if [[ "$scopes" != *project* || "$scopes" != *repo* ]]; then warn "scopes are '${scopes#*: }'; need project and repo"; return 1; fi
  say "verified: $login, scopes${scopes#*:}"
}

# pat_stage LOGIN VAR: mint and verify one classic PAT, keep it and its expiry in the env file.
pat_stage() {
  local who="$1" var="$2" exp_var="$2_EXPIRES"
  say "Actions cannot move cards on a user-owned board with GITHUB_TOKEN, a fine-grained token"
  say "or a GitHub App. Only a classic PAT with 'project' and 'repo' held by $who can."
  step "Make sure the browser is signed in as $who (avatar menu > Switch account if not)."
  open_url "https://github.com/settings/tokens/new?description=PROJECT_PAT%20task-manager&scopes=project,repo"
  step "Expiration: 90 days, or a custom date. Check that 'project' and 'repo' are ticked."
  step "Generate token, copy it now; GitHub never shows it again."
  ask_secret "$var" "Paste the $who token:"
  until verify_pat "${!var}" "$who"; do
    confirm "Paste again?" || break
    ask_secret "$var" "Paste the $who token:"
  done
  ask "$exp_var" "Expiry date from the token page (YYYY-MM-DD):"
  write_env "$var" "${!var}"
  write_env "$exp_var" "${!exp_var}"
}

banner "Task-manager: board clicks and tokens (oneezy/tools#14)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Auto-add to project on the tools board"
say "GitHub's built-in that puts every new issue on the board as it is opened. Browser-only:"
say "the API can read it and delete it, never turn it on."
open_url "$PROJECT_URL/workflows"
step "Click 'Auto-add to project' in the list on the left."
step "Click Edit. Repository: oneezy/tools. Filter: is:issue"
step "Click 'Save and turn on workflow'."
if autoadd_on; then
  say "Already on."
else
  printf '  %swaiting for the API to report it on (Ctrl-C stops)%s' "$DIM" "$RESET"
  until autoadd_on; do sleep 5; printf '.'; done
  printf '\n'; say "Auto-add to project is on."
fi

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Roadmap view: date fields and markers"
say "The roadmap draws phases as bars from Start to Due with milestones as markers."
say "Which fields it uses has no API, so this is a one-time click; the exact labels may differ."
open_url "$PROJECT_URL/views/4"
step "In the view's toolbar, 'Date fields': Start and Due."
step "'Markers': Milestones. Zoom: Month."
step "Save the view (the view menu next to its name > Save changes)."
pause "Done? Press Enter."

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Classic PAT for oneezy (repo secret PROJECT_PAT)"
pat_stage oneezy PROJECT_PAT_ONEEZY
set_secret PROJECT_PAT "$PROJECT_PAT_ONEEZY"     # the workflows on oneezy/tools read this one

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Classic PAT for layerdbiz"
pat_stage layerdbiz PROJECT_PAT_LAYERDBIZ
note "Kept in $ENV_FILE only. The bootstrap writes it into each layerdbiz repo as PROJECT_PAT"
note "when that repo gets the caller workflow."

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Claude Code token for the sizing agent"
say "The Claude Code GitHub action signs in with a long-lived subscription token."
step "This runs 'claude setup-token'. Finish the login in the browser it opens,"
step "then copy the token it prints (starts with sk-ant-oat01-)."
pause "Press Enter to run it."
claude setup-token || warn "claude setup-token failed; run it in another terminal, then paste here."
ask_secret CLAUDE_CODE_OAUTH_TOKEN "Paste the Claude token:"
write_env CLAUDE_CODE_OAUTH_TOKEN "$CLAUDE_CODE_OAUTH_TOKEN"
set_secret CLAUDE_CODE_OAUTH_TOKEN "$CLAUDE_CODE_OAUTH_TOKEN"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Rotation reminders"
say "One calendar event per PAT, a week before it expires."
for pair in "oneezy:${PROJECT_PAT_ONEEZY_EXPIRES:-}" "layerdbiz:${PROJECT_PAT_LAYERDBIZ_EXPIRES:-}"; do
  who=${pair%%:*}; exp=${pair#*:}
  [[ -n "$exp" ]] || { warn "no expiry recorded for $who, skipping"; continue; }
  if ! d=$(date -d "$exp - 7 days" +%Y%m%d 2>/dev/null); then warn "could not read '$exp' as a date for $who"; continue; fi
  open_url "https://calendar.google.com/calendar/render?action=TEMPLATE&text=Rotate+PROJECT_PAT+for+$who&dates=${d}/${d}&details=Expires+$exp.+Mint+a+new+classic+PAT+with+project+and+repo,+then+re-run+clis/task-manager-cli/setup-secrets.sh"
  step "Save the event for $who (token expires $exp)."
done
pause "Saved both? Press Enter."

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Verify"
say "The tool's read of the tools board (should say ok) and the secrets on $REPO:"
printf '\n'
pwsh -NoProfile -File clis/task-manager-cli/task-manager.ps1 status -Repo "$REPO" || warn "task-manager status failed"
printf '\n'
gh secret list -R "$REPO" || warn "gh secret list failed"
printf '\n'
pause

finish
