// Graph -> Mermaid flowchart. This module has no runtime imports: the CLI uses it in Node and
// inlines the compiled file into graph.html so the browser can re-render subgraphs.
import type { Edge, Flow, Graph, SkillNode } from "./types.js";

export interface MermaidOptions {
  /** HTML labels (fixed-size cards) and click handlers; false gives a portable .mmd */
  html?: boolean;
  /** skill id to focus on; null/undefined renders the whole library */
  focus?: string | null;
  /** how many call-hops downstream of the focus to include */
  depth?: number;
  /** draw sequential / parallel / loop boxes */
  flows?: boolean;
  /** include reference edges (dotted, no arrow) */
  references?: boolean;
  /** include suggests edges (a skill telling the human what to run next); default: only when focused */
  suggests?: boolean;
  /** show scripts/ and references/ files as small nodes */
  files?: boolean;
  direction?: "LR" | "TB";
}

const DEFAULTS: Omit<Required<MermaidOptions>, "suggests"> & { suggests?: boolean } = {
  html: false,
  focus: null,
  depth: 2,
  flows: true,
  references: false,
  files: false,
  direction: "LR",
};

export function toMermaid(graph: Graph, options: MermaidOptions = {}): string {
  const o = { ...DEFAULTS, ...options };
  const suggests = o.suggests ?? !!o.focus;
  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  const keepType = (t: Edge["type"]) => (t === "reference" ? o.references : t === "suggests" ? suggests : true);
  const included = o.focus ? neighborhood(graph, o.focus, o.depth, keepType) : new Set(graph.nodes.map((n) => n.id));
  const nodes = graph.nodes.filter((n) => included.has(n.id));
  const edges = graph.edges.filter((e) => included.has(e.source) && included.has(e.target) && keepType(e.type));
  const flows = o.flows
    ? graph.flows.filter((f) => included.has(f.owner) && (!o.focus || f.owner === o.focus || f.steps.includes(o.focus)))
    : [];

  const L: string[] = [];
  const links: string[] = []; // parallel array of edge kinds for linkStyle
  const link = (line: string, kind: string) => {
    L.push("  " + line);
    links.push(kind);
  };

  L.push(`flowchart ${o.direction}`);
  L.push("  %% generated by skills-viewer; every edge is traceable to a SKILL.md line in graph.json");

  const hasEdge = new Set<string>();
  for (const e of edges) {
    hasEdge.add(e.source);
    hasEdge.add(e.target);
  }
  for (const f of flows) {
    hasEdge.add(f.owner);
  }
  // a node with no visible edge is either truly standalone (no edge of any kind in the data)
  // or only reached by edges this view hides; group the latter under whoever points at it
  const hiddenSource = (id: string): string | null => {
    const e = graph.edges.find(
      (x) => x.target === id && x.source !== id && included.has(x.source) && !keepType(x.type),
    );
    return e ? e.source : null;
  };
  const entries = nodes.filter((n) => n.entry);
  const loose = nodes.filter((n) => !n.entry && !hasEdge.has(n.id));
  const standalone = loose.filter((n) => !hiddenSource(n.id));
  const hiddenGroups = new Map<string, SkillNode[]>();
  for (const n of loose) {
    const src = hiddenSource(n.id);
    if (src) hiddenGroups.set(src, [...(hiddenGroups.get(src) ?? []), n]);
  }
  const rest = nodes.filter((n) => !n.entry && hasEdge.has(n.id));

  if (entries.length) {
    L.push(`  subgraph entry ["▶ Entry points (you start here)"]`);
    L.push(`    direction ${o.direction === "LR" ? "TB" : "LR"}`);
    for (const n of entries) L.push("    " + nodeLine(n, o.html));
    L.push("  end");
  }
  for (const n of rest) L.push("  " + nodeLine(n, o.html));
  for (const [src, group] of hiddenGroups) {
    const label = suggests
      ? `mentioned by ${byId.get(src)?.name ?? src}`
      : `${byId.get(src)?.name ?? src} suggests these (turn on "suggests" to see the edges)`;
    L.push(`  subgraph hidden_${nid(src)} ["${esc(label)}"]`);
    L.push(`    direction TB`);
    for (const n of group) L.push("    " + nodeLine(n, o.html));
    L.push("  end");
  }
  if (standalone.length) {
    L.push(`  subgraph standalone ["Standalone (no links found)"]`);
    L.push(`    direction TB`);
    for (const n of standalone) L.push("    " + nodeLine(n, o.html));
    L.push("  end");
  }

  if (o.files) {
    for (const n of nodes) {
      for (const f of n.scripts) {
        const id = fileId(n.id, "s", f);
        L.push(`  ${id}[/"${esc(f)}"/]:::file`);
        link(`${nid(n.id)} -.- ${id}`, "file");
      }
      for (const f of n.references) {
        const id = fileId(n.id, "r", f);
        L.push(`  ${id}[["${esc(f)}"]]:::file`);
        link(`${nid(n.id)} -.- ${id}`, "file");
      }
    }
  }

  for (const e of edges) link(edgeLine(e), e.warning ? "warning" : e.type);

  flows.forEach((f, fi) => {
    const fid = `flow${fi + 1}`;
    const inst = (i: number) => `${fid}_${i + 1}`;
    const instNode = (i: number) => {
      const n = byId.get(f.steps[i]);
      return n ? instanceLine(inst(i), n, o.html) : `${inst(i)}["${esc(f.steps[i])}"]`;
    };
    if (f.kind === "sequential") {
      L.push(`  subgraph ${fid} ["${esc(f.label)}"]`);
      L.push(`    direction ${o.direction}`);
      for (let i = 0; i < f.steps.length; i++) L.push("    " + instNode(i));
      for (let i = 0; i < f.steps.length - 1; i++) link(`${inst(i)} -- "step ${i + 2}" --> ${inst(i + 1)}`, "flow");
      L.push(`    ${fid}_result(["result"]):::result`);
      link(`${inst(f.steps.length - 1)} --> ${fid}_result`, "flow");
      L.push("  end");
      link(`${nid(f.owner)} -- "step 1" --> ${inst(0)}`, "flow");
    } else if (f.kind === "parallel") {
      L.push(`  subgraph ${fid} ["⫴ ${esc(f.label)}"]`);
      L.push(`    direction ${o.direction}`);
      for (let i = 0; i < f.steps.length; i++) L.push("    " + instNode(i));
      L.push("  end");
      L.push(`  ${fid}_join(["join → report"]):::result`);
      for (let i = 0; i < f.steps.length; i++) {
        link(`${nid(f.owner)} --> ${inst(i)}`, "flow");
        link(`${inst(i)} --> ${fid}_join`, "flow");
      }
    } else {
      L.push(`  subgraph ${fid} ["↻ ${esc(clean(f.until ? "loop until " + f.until : f.label, 70))}"]`);
      L.push(`    direction ${o.direction}`);
      for (let i = 0; i < f.steps.length; i++) L.push("    " + instNode(i));
      for (let i = 0; i < f.steps.length - 1; i++) link(`${inst(i)} --> ${inst(i + 1)}`, "flow");
      link(`${inst(f.steps.length - 1)} -. "↻ again" .-> ${inst(0)}`, "loop");
      L.push("  end");
      link(`${nid(f.owner)} --> ${inst(0)}`, "flow");
    }
  });

  // styles
  L.push("  classDef auto fill:#e6f4ea,stroke:#2e7d32,color:#1b3d20");
  L.push("  classDef manual fill:#fff1e0,stroke:#e65100,color:#4a2600");
  L.push("  classDef background fill:#ede7f6,stroke:#5e35b1,color:#2a1a4d");
  L.push("  classDef entry stroke-width:3px");
  L.push("  classDef inst stroke-dasharray:4 3");
  L.push("  classDef result fill:#f5f5f5,stroke:#9e9e9e,color:#424242");
  L.push("  classDef file fill:#fafafa,stroke:#bdbdbd,color:#616161,font-size:11px");
  links.forEach((kind, i) => {
    const style = LINK_STYLES[kind];
    if (style) L.push(`  linkStyle ${i} ${style}`);
  });
  if (o.html) {
    for (const n of nodes) L.push(`  click ${nid(n.id)} call skillClick()`);
    flows.forEach((f, fi) => f.steps.forEach((_, i) => L.push(`  click flow${fi + 1}_${i + 1} call skillClick()`)));
  }
  return L.join("\n") + "\n";
}

const LINK_STYLES: Record<string, string> = {
  calls: "stroke:#1565c0,stroke-width:2px",
  suggests: "stroke:#6a1b9a,stroke-width:1.5px",
  prerequisite: "stroke:#2e7d32,stroke-width:2.5px",
  reference: "stroke:#9e9e9e,stroke-width:1px",
  warning: "stroke:#d32f2f,stroke-width:2px",
  flow: "stroke:#455a64,stroke-width:1.5px",
  loop: "stroke:#ef6c00,stroke-width:2px",
  file: "stroke:#bdbdbd,stroke-width:1px",
};

/** Skills reachable from the focus: everything downstream by `depth` hops, plus one hop upstream. */
export function neighborhood(
  graph: Graph,
  focus: string,
  depth: number,
  keepType: (t: Edge["type"]) => boolean,
): Set<string> {
  const keep = (e: Edge) => keepType(e.type);
  const set = new Set<string>([focus]);
  let frontier = [focus];
  for (let d = 0; d < depth && frontier.length; d++) {
    const next: string[] = [];
    for (const id of frontier) {
      for (const e of graph.edges)
        if (e.source === id && keep(e) && !set.has(e.target)) (set.add(e.target), next.push(e.target));
      for (const f of graph.flows)
        if (f.owner === id) for (const s of f.steps) if (!set.has(s)) (set.add(s), next.push(s));
    }
    frontier = next;
  }
  for (const e of graph.edges) if (e.target === focus && keep(e)) set.add(e.source);
  for (const f of graph.flows) if (f.steps.includes(focus)) set.add(f.owner);
  return set;
}

export function nid(id: string): string {
  return "n_" + id.replace(/[^a-zA-Z0-9]/g, "_");
}

function fileId(skill: string, kind: string, file: string): string {
  return `${nid(skill)}_${kind}_${file.replace(/[^a-zA-Z0-9]/g, "_")}`;
}

function nodeLine(n: SkillNode, html: boolean): string {
  // Mermaid accepts one class after ":::"; extra classes go on a separate "class" statement
  const extra = n.entry
    ? `
  class ${nid(n.id)} entry`
    : "";
  return `${nid(n.id)}["${label(n, html, false)}"]:::${n.mode}${extra}`;
}

function instanceLine(id: string, n: SkillNode, html: boolean): string {
  return `${id}["${label(n, html, true)}"]:::${n.mode}
  class ${id} inst`;
}

function label(n: SkillNode, html: boolean, instance: boolean): string {
  const badge = n.entry ? "▶ " : n.subSkill ? "↳ " : "";
  const modeWord = n.mode === "manual" ? "manual" : n.mode === "background" ? "model-only" : "auto";
  if (!html) {
    const d = truncate(n.description, instance ? 40 : 70);
    return esc(`${badge}${n.name}`) + (d ? `<br/><small>${esc(d)}</small>` : "");
  }
  const d = truncate(n.description, instance ? 60 : 110);
  return `<div class='sk sk-${n.mode}${instance ? " sk-inst" : ""}'><div class='sk-name'>${esc(badge + n.name)}</div><div class='sk-desc'>${esc(d)}</div><div class='sk-mode'>${modeWord}</div></div>`;
}

function edgeLine(e: Edge): string {
  const a = nid(e.source);
  const b = nid(e.target);
  switch (e.type) {
    case "calls":
      return e.warning ? `${a} -- "⚠ manual-only" --> ${b}` : `${a} --> ${b}`;
    case "suggests":
      return `${a} -.-> ${b}`;
    case "prerequisite":
      return `${a} ==> ${b}`;
    default:
      return `${a} -.- ${b}`;
  }
}

/** strip markdown emphasis/code and truncate, for subgraph titles */
function clean(s: string, n: number): string {
  return truncate(s.replace(/[*_`]+/g, "").replace(/\s+/g, " "), n);
}

function truncate(s: string, n: number): string {
  const t = s.replace(/\s+/g, " ").trim();
  return t.length > n ? t.slice(0, n - 1).trimEnd() + "…" : t;
}

/** Escape for a double-quoted Mermaid label. */
export function esc(s: string): string {
  return s.replace(/"/g, "#quot;").replace(/</g, "#lt;").replace(/>/g, "#gt;");
}
