#!/usr/bin/env python3
"""skills-sync: one skills repo, every harness, every project on this host.

Python 3.10+ stdlib only. Junctions on Windows (no admin), symlinks elsewhere.

  skills_sync.py                 layers + user (the default)
  skills_sync.py layers          rebuild .agents/skills and .claude/skills in the skills repo
  skills_sync.py user            one link per skill in ~/.claude/skills and ~/.agents/skills
  skills_sync.py projects        picker: copy skills into repos under the dev folder
  skills_sync.py unlink          remove the links this tool made in the user folders
  skills_sync.py status          what is linked, what is not

Options: --repo PATH  --home PATH  --dev PATH  --plan  --json  --projects a,b  --skills x,y  --copy
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

RESERVED = {"synced", ".system"}
GITIGNORE_HEADER = "# Generated by skills-sync: links to this repo's own skills in skills/<name>. Do not edit.\n"


# ---------------------------------------------------------------- link primitives

def is_link(path: Path) -> bool:
    if path.is_symlink():
        return True
    isjunction = getattr(os.path, "isjunction", None)
    return bool(isjunction and isjunction(str(path)))


def lexists(path: Path) -> bool:
    try:
        os.lstat(path)
        return True
    except OSError:
        return False


def link_target(path: Path) -> Path | None:
    try:
        raw = os.readlink(str(path))
    except OSError:
        return None
    if raw.startswith("\\\\?\\"):
        raw = raw[4:]
    return Path(raw)


def same_path(a: Path, b: Path) -> bool:
    return os.path.normcase(os.path.normpath(str(a))) == os.path.normcase(os.path.normpath(str(b)))


def under(path: Path, root: Path) -> bool:
    p = os.path.normcase(os.path.normpath(str(path)))
    r = os.path.normcase(os.path.normpath(str(root)))
    return p == r or p.startswith(r.rstrip("\\/") + os.sep)


def real(path: Path) -> Path:
    try:
        return Path(os.path.realpath(str(path)))
    except OSError:
        return path


def make_link(target: Path, link: Path) -> None:
    link.parent.mkdir(parents=True, exist_ok=True)
    if os.name == "nt":
        import _winapi  # stdlib, Windows only

        _winapi.CreateJunction(str(target), str(link))
    else:
        os.symlink(str(target), str(link), target_is_directory=True)


def remove_link(link: Path) -> None:
    try:
        os.rmdir(link)  # junctions and directory symlinks on Windows
    except OSError:
        os.unlink(link)


def is_skill_dir(path: Path) -> bool:
    return (path / "SKILL.md").is_file()


# ---------------------------------------------------------------- actions

@dataclass
class Action:
    kind: str  # link | relink | remove | replace-copy | copy | write | skip | conflict
    path: Path
    target: Path | None = None
    note: str = ""

    def line(self) -> str:
        mark = {"link": "+", "relink": "~", "remove": "-", "replace-copy": "~", "copy": "+", "write": "+", "skip": "=", "conflict": "!"}[self.kind]
        tail = f" -> {self.target}" if self.target else ""
        shown = f"{self.note.count(chr(10)) - 1} entries" if self.kind == "write" else self.note
        note = f"  ({shown})" if shown else ""
        return f"{mark} {self.kind:<12} {self.path}{tail}{note}"

    def as_dict(self) -> dict:
        return {"kind": self.kind, "path": str(self.path), "target": str(self.target) if self.target else None, "note": self.note}


@dataclass
class Report:
    actions: list[Action] = field(default_factory=list)

    def add(self, kind: str, path: Path, target: Path | None = None, note: str = "") -> Action:
        a = Action(kind, path, target, note)
        self.actions.append(a)
        return a

    def changes(self) -> list[Action]:
        return [a for a in self.actions if a.kind not in ("skip", "conflict")]

    def conflicts(self) -> list[Action]:
        return [a for a in self.actions if a.kind == "conflict"]


def apply(report: Report, plan: bool) -> None:
    if plan:
        return
    for a in report.actions:
        if a.kind == "link":
            make_link(a.target, a.path)
        elif a.kind == "relink":
            remove_link(a.path)
            make_link(a.target, a.path)
        elif a.kind == "remove":
            remove_link(a.path)
        elif a.kind == "replace-copy":
            shutil.rmtree(a.path)
            make_link(a.target, a.path)
        elif a.kind == "copy":
            if a.path.exists():
                shutil.rmtree(a.path)
            shutil.copytree(a.target, a.path)
        elif a.kind == "write":
            a.path.parent.mkdir(parents=True, exist_ok=True)
            a.path.write_text(a.note, encoding="utf-8")


# ---------------------------------------------------------------- the skills repo

@dataclass
class Repo:
    root: Path

    @property
    def own(self) -> Path:
        return self.root / "skills"

    @property
    def agents(self) -> Path:
        return self.root / ".agents" / "skills"

    @property
    def claude(self) -> Path:
        return self.root / ".claude" / "skills"

    def own_skills(self) -> list[Path]:
        if not self.own.is_dir():
            return []
        return sorted(p for p in self.own.iterdir() if p.is_dir() and is_skill_dir(p))

    def working_set(self) -> dict[str, Path]:
        """name -> real folder, for every entry in .agents/skills that holds a SKILL.md."""
        out: dict[str, Path] = {}
        if not self.agents.is_dir():
            return out
        for p in sorted(self.agents.iterdir()):
            if p.name.startswith(".") or p.name in RESERVED:
                continue
            if is_skill_dir(p):
                out[p.name] = real(p)
        return out


def ensure_link(report: Report, link: Path, target: Path, managed_root: Path, what: str) -> None:
    """Make `link` point at `target`. Never destroy a real folder; only manage links into managed_root."""
    if not lexists(link):
        report.add("link", link, target)
        return
    if is_link(link):
        current = link_target(link)
        if current and same_path(current, target):
            report.add("skip", link, note="ok")
        elif current and under(current, managed_root):
            report.add("relink", link, target, note=f"was {current}")
        else:
            report.add("conflict", link, note=f"{what}: link points outside the skills repo ({current}); left alone")
        return
    report.add("conflict", link, note=f"{what}: a real folder is in the way; left alone")


def layers(repo: Repo, report: Report) -> None:
    own = repo.own_skills()
    # 1. .agents/skills/<name> -> skills/<name>
    for skill in own:
        ensure_link(report, repo.agents / skill.name, skill, repo.root, "own skill")
    own_names = {s.name for s in own}
    if repo.agents.is_dir():
        for p in sorted(repo.agents.iterdir()):
            if is_link(p):
                t = link_target(p)
                if t and under(t, repo.own) and (p.name not in own_names or not t.exists()):
                    report.add("remove", p, note="stale link to a removed own skill")
    # 2. the ignore list for those links
    body = GITIGNORE_HEADER + "".join(f"/{n}/\n" for n in sorted(own_names)) if own_names else GITIGNORE_HEADER
    gi = repo.agents / ".gitignore"
    if not gi.is_file() or gi.read_text(encoding="utf-8") != body:
        report.add("write", gi, note=body)
    else:
        report.add("skip", gi, note="ok")
    # 3. .claude/skills/<name> -> real folder of every working-set entry
    pending = {s.name for s in own if not lexists(repo.agents / s.name)}
    working = repo.working_set()
    for name in own_names - set(working):
        if name in pending:
            working[name] = repo.own / name  # will exist once step 1 is applied
    for name, target in sorted(working.items()):
        link = repo.claude / name
        if lexists(link) and not is_link(link) and is_skill_dir(link):
            report.add("replace-copy", link, target, note="stale copy in the generated layer")
        else:
            ensure_link(report, link, target, repo.root, "claude layer")
    if repo.claude.is_dir():
        for p in sorted(repo.claude.iterdir()):
            if p.name not in working and is_link(p):
                t = link_target(p)
                if t and under(t, repo.root):
                    report.add("remove", p, note="no longer in .agents/skills")


# ---------------------------------------------------------------- the host's user folders

def user_dirs(home: Path) -> list[Path]:
    return [home / ".claude" / "skills", home / ".agents" / "skills"]


def user(repo: Repo, home: Path, report: Report, copy: bool = False) -> None:
    working = repo.working_set()
    for name in repo.own_skills():
        working.setdefault(name.name, name)  # layers may not have run yet
    for udir in user_dirs(home):
        for name, target in sorted(working.items()):
            if name in RESERVED:
                continue
            link = udir / name
            if copy:
                if link.exists() and not is_link(link):
                    report.add("skip", link, note="copy exists; use unlink to refresh")
                elif is_link(link):
                    report.add("conflict", link, note="is a link; remove it before --copy")
                else:
                    report.add("copy", link, target)
            else:
                ensure_link(report, link, target, repo.root, "user folder")
        if udir.is_dir():
            for p in sorted(udir.iterdir()):
                if p.name in working or not is_link(p):
                    continue
                t = link_target(p)
                if t and under(t, repo.root):
                    report.add("remove", p, note="skill no longer in the repo")


def unlink(repo: Repo, home: Path, report: Report) -> None:
    for udir in user_dirs(home):
        if not udir.is_dir():
            continue
        for p in sorted(udir.iterdir()):
            if is_link(p):
                t = link_target(p)
                if t and under(t, repo.root):
                    report.add("remove", p, note="made by skills-sync")


# ---------------------------------------------------------------- projects (committed copies)

def list_projects(dev: Path, repo: Repo) -> list[Path]:
    if not dev.is_dir():
        return []
    out = []
    for p in sorted(dev.iterdir()):
        if p.is_dir() and (p / ".git").exists() and not same_path(real(p), real(repo.root)):
            out.append(p)
    return out


def projects(repo: Repo, targets: list[Path], names: list[str] | None, report: Report) -> None:
    working = repo.working_set()
    chosen = {n: working[n] for n in (names or sorted(working)) if n in working}
    for proj in targets:
        for layer in (proj / ".agents" / "skills", proj / ".claude" / "skills"):
            for name, src in sorted(chosen.items()):
                dst = layer / name
                if is_link(dst):
                    report.add("conflict", dst, note="is a link; a project copy must be a real folder")
                elif dst.is_dir() and folder_hash(dst) == folder_hash(src):
                    report.add("skip", dst, note="ok")
                else:
                    report.add("copy", dst, src)


def folder_hash(folder: Path) -> str:
    import hashlib

    h = hashlib.sha256()
    for p in sorted(folder.rglob("*")):
        if p.is_file():
            h.update(str(p.relative_to(folder)).replace("\\", "/").encode())
            h.update(p.read_bytes())
    return h.hexdigest()


def pick(title: str, rows: list[str]) -> list[str]:
    """Arrow keys move, space toggles, a all/none, enter acts, q quits. Same keys as every tool in clis/."""
    if not sys.stdin.isatty():
        raise SystemExit("The picker needs a terminal. Pass --projects a,b instead.")
    cursor, checked = 0, set()
    while True:
        os.system("cls" if os.name == "nt" else "clear")
        print(title)
        print("  up/down move   space check   a all/none   enter run   q quit\n")
        for i, row in enumerate(rows):
            print(f"{'>' if i == cursor else ' '} [{'x' if i in checked else ' '}] {row}")
        key = keypress()
        if key == "up":
            cursor = (cursor - 1) % len(rows)
        elif key == "down":
            cursor = (cursor + 1) % len(rows)
        elif key == " ":
            checked ^= {cursor}
        elif key == "a":
            checked = set() if len(checked) == len(rows) else set(range(len(rows)))
        elif key in ("\r", "\n"):
            return [rows[i] for i in sorted(checked)]
        elif key == "q":
            return []


def keypress() -> str:
    if os.name == "nt":
        import msvcrt

        key = msvcrt.getwch()
        if key in ("\x00", "\xe0"):
            return {"H": "up", "P": "down"}.get(msvcrt.getwch(), "")
        return key.lower()
    import select
    import termios
    import tty

    fd = sys.stdin.fileno()
    previous = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        key = os.read(fd, 1).decode(errors="replace")
        if key == "\x1b" and select.select([fd], [], [], 0.1)[0]:
            return {"[A": "up", "[B": "down"}.get(os.read(fd, 2).decode(errors="replace"), "")
        return key.lower()
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, previous)


# ---------------------------------------------------------------- status

def status(repo: Repo, home: Path) -> dict:
    own = [p.name for p in repo.own_skills()]
    working = repo.working_set()
    third = sorted(n for n in working if n not in own)
    out = {"repo": str(repo.root), "own": own, "third_party": third, "claude_layer": {}, "user": {}}
    for name in working:
        p = repo.claude / name
        out["claude_layer"][name] = "link" if is_link(p) else "copy" if p.is_dir() else "missing"
    for udir in user_dirs(home):
        linked = [n for n in working if is_link(udir / n) and (t := link_target(udir / n)) and under(t, repo.root)]
        out["user"][str(udir)] = {"linked": len(linked), "missing": sorted(set(working) - set(linked))}
    return out


# ---------------------------------------------------------------- cli

def default_repo() -> Path:
    env = os.environ.get("SKILLS_REPO")
    if env:
        return Path(env)
    for c in (Path("V:/dev/skills"), Path.home() / "dev" / "skills"):
        if c.is_dir():
            return c
    return Path("V:/dev/skills")


def default_dev(repo: Path) -> Path:
    return Path(os.environ.get("DEV_ROOT") or repo.parent)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="skills-sync", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", nargs="?", default="all", choices=["all", "layers", "user", "projects", "unlink", "status"])
    ap.add_argument("--repo", type=Path, default=None, help="the skills repo checkout (default: $SKILLS_REPO, V:/dev/skills, ~/dev/skills)")
    ap.add_argument("--home", type=Path, default=None, help="home folder holding .claude and .agents (default: your home)")
    ap.add_argument("--dev", type=Path, default=None, help="folder whose git repos the projects command offers (default: the repo's parent)")
    ap.add_argument("--plan", action="store_true", help="show what would change; touch nothing")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--projects", default=None, help="comma-separated project folder names; skips the picker")
    ap.add_argument("--skills", default=None, help="comma-separated skill names for projects (default: all)")
    ap.add_argument("--copy", action="store_true", help="user: copy instead of link (hosts where links do not survive)")
    a = ap.parse_args(argv)

    repo = Repo(real(a.repo or default_repo()))
    home = real(a.home or Path.home())
    if not repo.root.is_dir():
        print(f"skills repo not found: {repo.root}", file=sys.stderr)
        return 2

    if a.command == "status":
        s = status(repo, home)
        if a.json:
            print(json.dumps(s, indent=2))
        else:
            print(f"repo {s['repo']}: {len(s['own'])} own, {len(s['third_party'])} third-party")
            missing = [n for n, v in s["claude_layer"].items() if v != "link"]
            print(f".claude/skills layer: {len(s['claude_layer']) - len(missing)} linked, {len(missing)} not")
            for udir, v in s["user"].items():
                print(f"{udir}: {v['linked']} linked, {len(v['missing'])} missing")
        return 0

    report = Report()
    if a.command in ("all", "layers"):
        step = Report()
        layers(repo, step)
        apply(step, a.plan)  # the user step reads the layer this one just built
        report.actions += step.actions
    if a.command in ("all", "user"):
        step = Report()
        user(repo, home, step, copy=a.copy)
        apply(step, a.plan)
        report.actions += step.actions
    if a.command == "unlink":
        unlink(repo, home, report)
        apply(report, a.plan)
    if a.command == "projects":
        dev = real(a.dev or default_dev(repo.root))
        available = list_projects(dev, repo)
        if a.projects:
            wanted = {n.strip() for n in a.projects.split(",") if n.strip()}
            chosen = [p for p in available if p.name in wanted]
            unknown = wanted - {p.name for p in chosen}
            if unknown:
                print(f"not a git repo under {dev}: {', '.join(sorted(unknown))}", file=sys.stderr)
                return 2
        else:
            names = pick(f"Copy skills from {repo.root} into which repos under {dev}?", [p.name for p in available])
            chosen = [p for p in available if p.name in names]
        skills = [s.strip() for s in a.skills.split(",")] if a.skills else None
        projects(repo, chosen, skills, report)
        apply(report, a.plan)

    if a.json:
        print(json.dumps({"plan": a.plan, "actions": [x.as_dict() for x in report.actions]}, indent=2))
    else:
        for x in report.actions:
            if x.kind != "skip":
                print(x.line())
        ok = sum(1 for x in report.actions if x.kind == "skip")
        verb = "would change" if a.plan else "changed"
        print(f"{'plan: ' if a.plan else ''}{len(report.changes())} {verb}, {ok} already right, {len(report.conflicts())} left alone")
    return 0


if __name__ == "__main__":
    sys.exit(main())
